version: '3.9'

services:

    minio:
        image: minio/minio:latest
        command: "server /data --console-address :9090"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        ports:
            - "9001:9000"
            - "9093:9090"
        restart: always
        volumes:
            - ./minio_data:/data
        container_name: miniopython

    spark-master:
        image: bitnami/spark:latest
        ports:
            - "8084:8084"
            - "7078:7078"
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        container_name: spark-master_python

    spark-worker_1:
        image: bitnami/spark:latest
        ports:
            - "8085:8085"
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        depends_on:
            - spark-master
        container_name: spark-worker_1_python

    spark-worker_2:
        image: bitnami/spark:latest
        ports:
            - "8086:8086"
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        depends_on:
            - spark-master
        container_name: spark-worker_2_python
