≈≈version: '3.9'

services:

    minio:
        image: minio/minio:latest
        command: "server /data --console-address :9090"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        ports:
            - "9001:9000"
            - "9093:9090"
        restart: always
        volumes:
            - ./minio_data:/data
        container_name: miniopython
